### PR TITLE
Allow for swipe dismiss gesture in the WelcomeController

### PR DESCRIPTION
**Pull request by Luki120**

### CODE REVIEW

**Comment by camieeh** [comment]
no

**Comment by Luki120** [comment]
Heh, look what we have here, seems like Diary's welcome controller can now be dismissed with a swipe. I thought we couldn't "chingi yiir mind", and conveniently enough that part isn't open source, unbelievable. At least you opened your mind a bit and stopped playing god, you were just too proud to accept a pull request from me and instead decided to fuck me over. But thank youuu for making this change 🥰🥰🥰.

**Comment by camieeh** [comment]
perhaps you should stop lying for once

image

image

**Comment by Luki120** [comment]
Nobody yelled you anything. All what we did was telling you how that would be a good feature. You just decided to shut down or whatever. You felt like shit? Imagine having expectations about such a small thing and watching them go down due to such a harsh close and comment, jfc.

**Comment by camieeh** [comment]
interesting to see that you still don't know how sensitive i am

i said no twice and then you make a pull request, what did you honestly expect?

**Comment by Luki120** [comment]
Yeah you're not the only one.

Not that for sure, you couldve left it opened forever. Maybe you should switch places and think of it again. How'd you feel if Ethan were to do the same thing for example.

And what made you change your mind? Since you were so decided.

**Comment by camieeh** [comment]
i wouldn't have made such a big thing out of it, it's up to him to accept it or not, i simply offered improvements

for my mind to change you just have to give me some time and my smol brain will handle it by itself

**Comment by camieeh** [comment]
i guess you want an answer for the "no" as well

image

**Comment by Luki120** [comment]
I was already done but okay.

**Comment by Luki120** [comment]
Hey, I kept thinking about this. Would you mind locking the conversation here? In case anyone with mean intentions decides to come and attack either one of us. Probably unlikely but I'll appreciate it. Also, I'm again very sorry with my first approach here after what happened, truly. Have a nice day Alexa, if I can still call you like that heh.

**Comment by camieeh** [comment]
if it makes you happy 🪴

**Pull request closed without merging**
